import type { Incident } from './types'

function createRelativeTimestamp(daysAgo: number, hour: number, minute: number) {
  const date = new Date()
  date.setDate(date.getDate() - daysAgo)
  date.setHours(hour, minute, 0, 0)
  return date.toISOString()
}

export function createExampleIncidents(): Incident[] {
  return [
    {
      id: 'demo-001',
      problem: 'Checkout timeout during traffic burst',
      rootCauses: ['Database connection pool saturation', 'Cache invalidation gap'],
      topics: ['Payments', 'Database', 'API'],
      fix: 'Raised pool limits, added request shedding, and warmed hot cache keys before the sale window.',
      status: 'Resolved',
      impact: 'Critical',
      createdAt: createRelativeTimestamp(0, 9, 15),
      description: 'The checkout API exceeded the timeout budget for 12 minutes when promo traffic peaked across EU and US.',
    },
    {
      id: 'demo-002',
      problem: 'API latency spike in EU region',
      rootCauses: ['Memory leak in worker process', 'Missing alert coverage'],
      topics: ['API', 'Infrastructure', 'Monitoring'],
      fix: 'Rolled the leaking worker deployment, added heap usage alerts, and enabled canary monitoring.',
      status: 'In Progress',
      impact: 'High',
      createdAt: createRelativeTimestamp(1, 14, 20),
      description: 'p95 latency crossed 2.8s because image transformation workers kept accumulating unreleased buffers.',
    },
    {
      id: 'demo-003',
      problem: 'Invoice workers stuck after deploy',
      rootCauses: ['Queue consumer crash loop', 'Missing alert coverage'],
      topics: ['Payments', 'Workers', 'Monitoring'],
      fix: 'Pinned the worker image, restored dead-letter retries, and added a queue depth alert.',
      status: 'Resolved',
      impact: 'High',
      createdAt: createRelativeTimestamp(2, 11, 5),
      description: 'Consumers restarted continuously after a deploy and invoices stopped processing for 38 minutes.',
    },
    {
      id: 'demo-004',
      problem: 'Auth token refresh failures',
      rootCauses: ['Expired secret rotation', 'Terraform drift after manual hotfix'],
      topics: ['Authentication', 'Security', 'Deployments'],
      fix: 'Re-synced secret versions across environments and removed the manual config drift from infrastructure code.',
      status: 'Resolved',
      impact: 'High',
      createdAt: createRelativeTimestamp(3, 8, 40),
      description: 'Refresh token validation failed after production picked up a newer signing secret than the API gateway.',
    },
    {
      id: 'demo-005',
      problem: 'Search results serving stale documents',
      rootCauses: ['Cache invalidation gap', 'Memory leak in worker process'],
      topics: ['Search', 'API', 'Data Pipeline'],
      fix: 'Shortened index cache TTLs and patched the worker leak in the document enrichment job.',
      status: 'In Progress',
      impact: 'Medium',
      createdAt: createRelativeTimestamp(4, 16, 10),
      description: 'Customers saw outdated search documents because fresh index snapshots were not propagated quickly enough.',
    },
    {
      id: 'demo-006',
      problem: 'CDN requests hitting wrong origin',
      rootCauses: ['DNS record mismatch'],
      topics: ['CDN', 'Networking', 'Customer Portal'],
      fix: 'Corrected the origin alias, lowered TTLs temporarily, and added a smoke test for edge routing.',
      status: 'Resolved',
      impact: 'Critical',
      createdAt: createRelativeTimestamp(5, 10, 30),
      description: 'Traffic for one regional edge POP was routed to a decommissioned origin after a DNS update.',
    },
    {
      id: 'demo-007',
      problem: 'Customer dashboard loading slowly',
      rootCauses: ['Missing alert coverage'],
      topics: ['Frontend', 'Monitoring', 'Customer Portal'],
      fix: 'Added render timing alerts and introduced dashboard query budgeting for the slowest widgets.',
      status: 'Open',
      impact: 'Medium',
      createdAt: createRelativeTimestamp(6, 13, 45),
      description: 'Synthetic checks never alerted on the gradual regression, even though customer dashboards crossed 6s load time.',
    },
    {
      id: 'demo-008',
      problem: 'Checkout timeout during traffic burst',
      rootCauses: ['Database connection pool saturation'],
      topics: ['Payments', 'Database', 'API'],
      fix: 'Shifted background jobs away from the primary cluster and rebalanced connection pool reservations.',
      status: 'Closed',
      impact: 'Critical',
      createdAt: createRelativeTimestamp(7, 17, 5),
      description: 'A similar traffic burst one week earlier exhausted database connections before autoscaling reacted.',
    },
    {
      id: 'demo-009',
      problem: 'API latency spike in EU region',
      rootCauses: ['Memory leak in worker process'],
      topics: ['API', 'Infrastructure'],
      fix: 'Reduced batch sizes and restarted the transformer workers to stabilize memory usage.',
      status: 'Closed',
      impact: 'High',
      createdAt: createRelativeTimestamp(8, 9, 50),
      description: 'The first latency spike pattern was traced to the same long-lived worker pool that later regressed again.',
    },
    {
      id: 'demo-010',
      problem: 'Search results serving stale documents',
      rootCauses: ['Cache invalidation gap', 'Terraform drift after manual hotfix'],
      topics: ['Search', 'Deployments', 'Data Pipeline'],
      fix: 'Moved the index CDN rule into code and added post-deploy cache purge verification.',
      status: 'Closed',
      impact: 'Medium',
      createdAt: createRelativeTimestamp(9, 15, 35),
      description: 'A manual rule change skipped the cache purge step and left document snapshots stale for almost an hour.',
    },
    {
      id: 'demo-011',
      problem: 'Deployment rollback failed in staging',
      rootCauses: ['Cache invalidation gap'],
      topics: ['Deployments', 'Platform Engineering'],
      fix: 'Cleared stale artifacts before rollback and codified the deployment asset cache policy.',
      status: 'Resolved',
      impact: 'Low',
      createdAt: createRelativeTimestamp(10, 12, 25),
      description: 'Rollback requests kept serving cached bundles from the failed release, masking whether the rollback worked.',
    },
    {
      id: 'demo-012',
      problem: 'Invoice workers stuck after deploy',
      rootCauses: ['Queue consumer crash loop', 'Memory leak in worker process'],
      topics: ['Workers', 'Deployments', 'Payments'],
      fix: 'Added process supervision, reduced in-memory batch sizes, and improved deploy health checks.',
      status: 'Closed',
      impact: 'High',
      createdAt: createRelativeTimestamp(11, 18, 0),
      description: 'A batch processor leaked memory after deploy and eventually triggered a crash loop in the invoice queue consumers.',
    },
    {
      id: 'demo-013',
      problem: 'Customer dashboard loading slowly',
      rootCauses: ['Database connection pool saturation'],
      topics: ['Frontend', 'Database', 'Customer Portal'],
      fix: 'Split a heavy reporting query and moved secondary widgets to cached read replicas.',
      status: 'Resolved',
      impact: 'Medium',
      createdAt: createRelativeTimestamp(12, 10, 55),
      description: 'A dashboard release introduced a reporting query pattern that overused the shared connection pool.',
    },
    {
      id: 'demo-014',
      problem: 'Auth token refresh failures',
      rootCauses: ['Expired secret rotation', 'Missing alert coverage'],
      topics: ['Authentication', 'Security', 'Monitoring'],
      fix: 'Added secret expiry dashboards and rotation rehearsal checks before the next credential rollover.',
      status: 'Closed',
      impact: 'High',
      createdAt: createRelativeTimestamp(13, 7, 35),
      description: 'The previous rotation missed alerting for near-expiry credentials, so the issue was discovered by customers first.',
    },
  ]
}
